import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MainInput from "../components/MainInput";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Gifty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <MainInput />
      </>
    </div>
  );
}
